### ISSUE TITLE
operatorが正しく動作しない

### ISSUE THREAD

**Issue by stu2005** [Chinachu/Chinachu#368]
gamma installationにしたがってRaspberry Pi3(Raspbian Buster)にインストール、pm2へのスタートアップ登録を済ませた後に、起動しようとすると下記のエラーが出力されてoperatorが正しく動きません。
```
uncaughtException: Error: The module '/home/kagemo/chinachu/node_modules/diskusage/build/Release/diskusage.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:70:39)    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/kagemo/chinachu/node_modules/diskusage/index.js:1:76)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```
operatorを正しく動かす方法を教えてください。

**Comment by akimasa** [comment]
> Please try re-compiling or re-installing
> the module (for instance, using `npm rebuild` or `npm install`).

エラーメッセージに上記のような解決例があるので`npm rebuild`か`npm install`を実行してみてはいかがでしょうか？

**Comment by stu2005** [comment]
そちらは既に実行していますが解決しませんでした。原因は多分僕の場合nodejsをnでインストールしているので、通常の方法でやっても上手くいかないものと思われます。

**Comment by akimasa** [comment]
例えば、`export PATH=/home/kagemo/chinachu/.nave:$PATH`を実行してから`npm rebuild`か`npm install`を実行してみてはいかがでしょう？
[processes.json](https://github.com/Chinachu/Chinachu/blob/gamma/processes.json)によればPM2で起動する場合、.nave/nodeを使ってChinachuを実行しているようです。.naveにパスを通せば.naveにあるnodeが使われるので、モジュールバージョンの不一致が解消されると思います。

これでもダメなら`/home/kagemo/chinachu/`以下を削除して入れなおしてみると良いかもしれません。
> 原因は多分僕の場合nodejsをnでインストールしているので

よくわからないのでもう少し詳しく教えてください。
具体的にどんなコマンドを実行してインストールしたのでしょうか？

**Comment by stu2005** [comment]
解決したので閉じます。
