### ISSUE TITLE
./chinachu update でエラー

### ISSUE THREAD

**Issue by stu2005** [Chinachu/Chinachu#377]
**どのようなバグ(?)ですか**
./chinachu updateすると下記のエラーが出ます。
```
Client {
  basePath: '/api',
  docsPath: '/docs',
  priority: 0,
  host: '',
  port: 40772,
  socketPath: '/usr/local/mirakurun/run/mirakurun.sock',
  userAgent: 'Chinachu/0.10.3-gamma.0 (scheduler)',
  _userAgent: 'MirakurunClient/3.5.0 Node/v14.15.4 (linux)'
}
internal/fs/utils.js:779
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (1511)
    at Object.writeFileSync (fs.js:1460:5)
    at createPidFile (/home/pi/chinachu/app-scheduler.js:96:5)
    at /home/pi/chinachu/app-scheduler.js:670:3
    at isRunning (/home/pi/chinachu/app-scheduler.js:120:3)
    at Object.<anonymous> (/home/pi/chinachu/app-scheduler.js:664:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
failed somehow
```
**再現方法**
開発メンバーが再現するための手順を教えてください:
1. `./chinachu installer`を実行
2. `./chinachu update`を実行
3. See error

**期待する動作**
EPGの取得

**再現環境 (できるだけ詳しく):**
 - OS: raspbian buster
 - CPU: armhf
 - Version gamma最新

**Comment by kanreisa** [comment]
> `Node/v14.15.4`

Node.js v14 では動かないので Node.js v10 を使用してください。

**Comment by stu2005** [comment]
申し訳ないです.....

**Comment by kanreisa** [comment]
とんでもないです
ログを貼っていただいたおかげですぐにわかりました

**Comment by stu2005** [comment]
EPGStationと併用したかったのでdocker使って解決しました
