### ISSUE TITLE
スケジューラーのログに"TypeError [ERR_INVALID_ARG_TYPE]"などと報告される

### ISSUE THREAD

**Issue by hts-ozeki** [Chinachu/Chinachu#387]
スケジューラーのログに
```
internal/fs/utils.js:785
throw new ERR_INVALID_ARG_TYPE(
^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (多分PIDの数字)
at Object.writeFileSync (fs.js:1517:5)
at createPidFile (/home/recorder/Chinachu/app-scheduler.js:96:5)
at /home/recorder/Chinachu/app-scheduler.js:670:3
at isRunning (/home/recorder/Chinachu/app-scheduler.js:120:3)
at Object. (/home/recorder/Chinachu/app-scheduler.js:664:1)
at Module._compile (internal/modules/cjs/loader.js:1068:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
at Module.load (internal/modules/cjs/loader.js:933:32)
at Function.Module._load (internal/modules/cjs/loader.js:774:14)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
code: 'ERR_INVALID_ARG_TYPE'
}
```
と報告されます。

何もしなくてもChinachu起動時に報告されますが、できれば
`echo '[]' > rules.json`
などとルールを空にしておいたほうが、ログが減ってわかりやすいです。

再現環境
 OS: Linux 4.18.0-305.el8.x86_64 CentOS Stream 8
 userAgent: 'Chinachu/0.10.3-gamma.0 (scheduler)',
 _userAgent: 'MirakurunClient/3.6.0 Node/v14.17.0 (linux)'

app-scheduler.jsにパッチしたらエラー報告されなくなりました。
```
--- Chinachu-orig/app-scheduler.js      2021-07-19 22:13:14.000000000 +0900
+++ Chinachu/app-scheduler.js   2021-07-21 04:59:47.401170866 +0900
@@ -93,7 +93,7 @@

 // PID file operation
 function createPidFile() {
-       fs.writeFileSync(PID_FILE, process.pid);
+       fs.writeFileSync(PID_FILE, process.pid.toString());
 }

 function deletePidFile() {
```

**Comment by kanreisa** [comment]
こんにちは

再現環境に書いていただいたものはログからコピペしたものだと思いますが、

> _userAgent: 'MirakurunClient/3.6.0 Node/v14.17.0 (linux)'

ここが本来は `_userAgent: 'MirakurunClient/3.6.0 Node/v10.23.0 (linux)'` となるはずです。

（Node.js v14 で動作させるのであればその修正は正しいのですが、全くテストされていないため他にも不具合が発生する可能性があります。）
一旦修正を元に戻していただいて、
```
./chinachu installer
```
を実行して専用の Node.js を再インストールしてみてください。
```
./chinachu update
```
を実行して正常に動作することを確認してください。

**Comment by hts-ozeki** [comment]
Node.jsを自前でアップデートしてしまいましたので、バグとは言えないですね。
失礼しました。

**Comment by kanreisa** [comment]
グローバル環境の Node.js は v14 でも問題ありませんが、
Chinachu 内部で使用するものは v10 である必要があります。
どうぞよろしくお願いいたします。
